### ISSUE TITLE
API information

### ISSUE THREAD

**Issue by metawee** [Ruqyai/ChatBard#1]
We did not understand what the following information is required for? Can you add a link to each point?

- urlChatRESTApiAr
- urlSummarizeChatRESTApiAr
- urlChatApi
-accessToken
- urlSummarizeChatApi

**Comment by Ruqyai** [comment]
Hi @metawee 
I will incur charges from GCP for each request, so I've chosen to keep it hidden. If you want to create your own API, I've explained that in this guide:
https://github.com/Ruqyai/ChatBard/tree/main/FlaskApp-Python#to-use-the-deployment-api-endpoints

**Comment by metawee** [comment]
Found it yesterday. Thank you it helped me a lot

But a problem appears to me

upstream connect error or disconnect/reset before headers. reset reason: connection termination

I don't know what the reason is. Also, the main.py file contains 5 errors

Unable to import 'vertexai'pylint(import-error)
Unable to import 'vertexai.preview.language_models'pylint(import-error)
Unable to import 'vertexai.preview.language_models'pylint(import-error)
Unable to import 'var'pylint(import-error)
Unable to import 'deep_translator'pylint(import-error)

**Comment by metawee** [comment]
You solved the problem by
pip install deep_translator
pip install google-cloud-aiplatform

But it's still a problem
Unable to import 'var'pylint(import-error)

**Comment by metawee** [comment]
Hi @Ruqyai 

Found it yesterday. Thank you it helped me a lot

But a problem appears to me

upstream connect error or disconnect/reset before headers. reset reason: connection termination

**Comment by wiseroad-co** [comment]
Hey @Ruqyai 

It doesn't work for me either and a message appears

https://chatappwiseroad-dc65ism5ta-uc.a.run.app/

Service Unavailable

**Comment by Ruqyai** [comment]
Read the log file to know the reason

**Comment by wiseroad-co** [comment]
Unable to import 'var' pylint(import-error)
<img width="762" alt="Screenshot 2023-09-30 at 11 12 59 PM" src="https://github.com/Ruqyai/ChatBard/assets/146486927/c3690a41-6509-44b9-8f8e-92f26bb254d1">

**Comment by metawee** [comment]
Thank you, Ruqiya. It was a great effort from you and now it is working successfully for me
